spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/customer_db;AUTO_SERVER=true
      driver-class-name: org.h2.Driver
      username: sa
      password: manage
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

messaging:
  queue: customerQueue
  routingKey: CustomerCreated
  exchange: customerExchange

spring:
  profiles: dev
  
customer-service:
  firstName: DEV-FirstNameNF
  lastName: DEV-LastName
  email: dev.default@email.com
  
spring:
  profiles: qa
 
customer-service:
  firstName: QA-FirstName
  lastName: QA-LastName
  email: qa.default@email.com 
  


spring:
  profiles: prod
 
customer-service:
  firstName: PROD-FirstName
  lastName: PROD-LastName
  email: prod.default@email.com
