spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/salesorder_db;AUTO_SERVER=true
      driver-class-name: org.h2.Driver
      username: sa
      password: manage
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

messaging:
  queue: customerQueue
  routingKey: CustomerCreated
  exchange: customerExchange

logging:
  level:
    org:
      hibernate:
        sql: debug 
        
---

spring:
  profiles: dev
  
salesorder-service:
  message: dev-default
  
---

spring:
  profiles: qa
 
salesorder-service:
  message: qa-default
  
---

spring:
  profiles: prod
 
salesorder-service:
  message: default
  
